### ISSUE TITLE
Length balance

### ISSUE THREAD

**Issue by tsunyoku** [tsunyoku/akatsuki-pp#9]
Current length balance is too rewarding on some maps as it doesn't factor anything purely than it's length, we need ideas of more factors which deal with this

**Comment by CursorDance** [comment]
The pp of lengths could be based on the overall difficulty of the map, and going gradually (linearly) less over time. Of course it will need a static number as a set number(time of the map both on dt and nomod) and after the threshold it gradually goes up until reaching a certain number that goes back into static.

Basically lengthy map of 10min will still reward pp without being underweight due to the length of time nerf. All easy long maps won't give as much pp as they do at the moment since it wouldn't be based solely on the lengths and go gradually higher. And it would be based on the actual difficulty of the map without being based solely on the length.
